services:
  compressor-ai:
    build: .
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///data/compressor_system.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s